config/routes.rb
Slip::Application.routes.draw do
  resources :facet_values

  resources :facets

  resources :products do
  end
  

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :users
    ActiveAdmin.routes(self)
end

app/models/facet.rb
class Facet < ActiveRecord::Base
  has_many :facet_values
  accepts_nested_attributes_for :facet_values, allow_destroy: true
end

app/controllers/facets_controller.rb
class FacetsController < ApplicationController
  before_action :set_facet, only: [:show, :edit, :update, :destroy]

  # GET /facets
  # GET /facets.json
  def index
    @facets = Facet.all
  end

  # GET /facets/1
  # GET /facets/1.json
  def show
  end

  # GET /facets/new
  def new
    @facet = Facet.new
  end

  # GET /facets/1/edit
  def edit
  end

  # POST /facets
  # POST /facets.json
  def create
    @facet = Facet.new(facet_params)

    respond_to do |format|
      if @facet.save
        format.html { redirect_to @facet, notice: 'Facet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @facet }
      else
        format.html { render action: 'new' }
        format.json { render json: @facet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facets/1
  # PATCH/PUT /facets/1.json
  def update
    respond_to do |format|
      if @facet.update(facet_params)
        format.html { redirect_to @facet, notice: 'Facet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @facet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facets/1
  # DELETE /facets/1.json
  def destroy
    @facet.destroy
    respond_to do |format|
      format.html { redirect_to facets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_facet
      @facet = Facet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def facet_params
      params.require(:facet).permit(:name)
    end
end

app/helpers/facets_helper.rb
module FacetsHelper
end

app/views/facets/_form.html.erb
<%= simple_form_for(@facet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/facets/edit.html.erb
<h1>Editing facet</h1>

<%= render 'form' %>

<%= link_to 'Show', @facet %> |
<%= link_to 'Back', facets_path %>

app/views/facets/index.html.erb
<h1>Listing facets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @facets.each do |facet| %>
      <tr>
        <td><%= facet.name %></td>
        <td><%= link_to 'Show', facet %></td>
        <td><%= link_to 'Edit', edit_facet_path(facet) %></td>
        <td><%= link_to 'Destroy', facet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Facet', new_facet_path %>

app/views/facets/new.html.erb
<h1>New facet</h1>

<%= render 'form' %>

<%= link_to 'Back', facets_path %>

app/views/facets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @facet.name %>
</p>

<%= link_to 'Edit', edit_facet_path(@facet) %> |
<%= link_to 'Back', facets_path %>